export const ADDMATERI = "ADDMATERI";
export const GETMATERI = "GETMATERI";
export const GETDETAILMATERI = "GETDETAILMATERI";
export const DELETEFILEMATERI = "DELETEFILEMATERI";
export const UPDATEMATERI = "UPDATEMATERI";