export const DATAKELAS = "DATAKELAS";
export const TAMBAHKELAS = "TAMBAHKELAS";
export const EDITKELAS = "EDITKELAS";
export const GETCLASSBYTEACHERID = "DETAILCLASSBYTEACHERID";
export const DATAJK = "DATAJK";
export const DATAJABATAN = "DATAJABATAN";
export const DATAMAPEL = "DATAMAPEL";